### ISSUE TITLE
Footer - Girl Scouts of Western Ohio

### ISSUE THREAD

**Issue by dflynn15** [sparkbox/gswo-workshop#13]
Update the footer link to the "Girl Scouts of Western Ohio" instead of Girls Scouts of the USA.

Updated link: http://www.gswo.org/

**Comment by kaseybon** [comment]
**Pages to update**

- [ ] index.html
- [ ] prerequisites.html
- [ ] agenda.html
- [ ] example-site.html
- [ ] templates.html
