### ISSUE TITLE
Point domain name to GitHub pages

### ISSUE THREAD

**Issue by bryanbraun** [sparkbox/gswo-workshop#15]
~~It currently points to: http://gswo.seesparkbox.com/ (broken)~~
~~It should point to: http://sparkbox.github.io/gswo-workshop/ (on github pages & working)~~

Point http://gswo.seesparkbox.com to http://sparkbox.github.io/gswo-workshop

**Comment by kaseybon** [comment]
I wouldn't worry about updating the link in the README. We just need to update the domain name, it's still pointing to Divshot.

**Comment by bryanbraun** [comment]
Ok. So for the purposes of this issue we need:
- [ ] Add the CNAME file to this repo
- [ ] Update the DNS record accordingly

**Comment by kaseybon** [comment]
That should be it
