### ISSUE TITLE
Prerequisites Page

### ISSUE THREAD

**Issue by kaseybon** [sparkbox/gswo-workshop#16]
Content edits for [`prerequisites.html`](http://sparkbox.github.io/gswo-workshop/prerequisites.html)

- [x] Remove prerequisites for Divshot and Sublime
- [x] Add prerequisite: [Create a free CodePen Account](https://codepen.io/signup/free)

**Comment by kaseybon** [comment]
@emilykggray or @meljeans  Are there any other requirements we need to add?

- Bring a laptop
- Turn in any paperwork/permission slips
- Things I can't think of at the moment

**Comment by iAmNathanJ** [comment]
@kaseybon Do you mind if we apprentices pick up some of these quick fixes?

**Comment by kaseybon** [comment]
Feel free to work on which ever issues you want, just assign it to yourself so no one else picks it up. 

Also, for this page you might want to check in with either @meljeans or @emilykggray to make sure we don't need any other updates.

**Comment by kaseybon** [comment]
I went ahead and merged this. If we need to add more to the prereq page we can create a new issue.
