### ISSUE TITLE
Agenda Page

### ISSUE THREAD

**Issue by kaseybon** [sparkbox/gswo-workshop#17]
Content changes for [`agenda.html`](http://sparkbox.github.io/gswo-workshop/agenda.html)

- [ ] Update date of workshop to **Saturday, February 27, 2016**

**Comment by kaseybon** [comment]
@meljeans or @emilykggray Do we need to make any other updates to the agenda?

**Comment by meljeans** [comment]
- [ ] Change times to reflect [updated agenda](https://docs.google.com/document/d/1BvMwrRT5ym1azVfbfFEZZqKxpQt5_7yIGNEo1xOIHWQ/edit) - (Content is shorter, lunch is earlier, etc.)
- [ ] Add 2:30 - 3P new addition - Final Site Tweaks / Open Work Time
- [ ] Change last 30 min from testing & launch to "Launch & Share Projects"

**Comment by kaseybon** [comment]
@boomingbrake I'm going to assign this one to you. There are changes in both my comment and Melissa's. Once you get it done and make a PR assign it to me and we will schedule time to get it merged in!

**Comment by meljeans** [comment]
Can you be sure to let me know when there is a PR or is it merged so I can have a final look? Thanks!
