### ISSUE TITLE
Update CodePen Links

### ISSUE THREAD

**Issue by kaseybon** [sparkbox/gswo-workshop#43]
Templates:
---------------
- [x] One Column Template: http://codepen.io/team/sparkbox/pen/MKxogW?editors=110
- [x] Right Sidebar Template: http://codepen.io/team/sparkbox/pen/MKxogY?editors=110
- [x] Full Width Template: http://codepen.io/team/sparkbox/pen/KVEmOj?editors=110

@iAmNathanJ here is the first batch of links to update in `/templates.html`

**Comment by kaseybon** [comment]
Example Site:
------------------
Links to update in `/example-site.html`

- [ ] Site Content: http://codepen.io/team/sparkbox/pen/rxRwOe?editors=100
- [ ] Site Content w/Markup: http://codepen.io/team/sparkbox/pen/yewXYy?editors=100
- [ ] Site Content w/Styles: http://codepen.io/team/sparkbox/pen/pgYwjo?editors=110

**Comment by iAmNathanJ** [comment]
I think that's done @kaseybon Let me know what else I can do for you. :smile:
